import React, { useState, useEffect } from 'react';
import { AlertTriangle, Clock, Users, Send, Zap, MapPin, CheckCircle, AlertCircle, XCircle } from 'lucide-react';

interface EmergencyIncident {
  id: string;
  type: 'fire' | 'medical' | 'security' | 'weather' | 'lockdown';
  severity: 'low' | 'medium' | 'high' | 'critical';
  location: string;
  description: string;
  timestamp: string;
  status: 'active' | 'resolved' | 'monitoring';
  affectedStudents: number;
  notificationsSent: number;
}

const EmergencyDashboard: React.FC = () => {
  const [incidents, setIncidents] = useState<EmergencyIncident[]>([
    {
      id: '001',
      type: 'fire',
      severity: 'high',
      location: 'Science Building - 3rd Floor',
      description: 'Fire alarm activated in chemistry lab',
      timestamp: '2025-01-27 14:23:45',
      status: 'active',
      affectedStudents: 156,
      notificationsSent: 312
    },
    {
      id: '002',
      type: 'weather',
      severity: 'medium',
      location: 'Campus-wide',
      description: 'Severe weather warning - thunderstorm approaching',
      timestamp: '2025-01-27 13:45:12',
      status: 'monitoring',
      affectedStudents: 2847,
      notificationsSent: 5694
    }
  ]);

  const [newIncident, setNewIncident] = useState({
    type: 'medical' as const,
    severity: 'medium' as const,
    location: '',
    description: ''
  });

  const [aiMessage, setAiMessage] = useState('');
  const [isGeneratingMessage, setIsGeneratingMessage] = useState(false);

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'bg-red-100 text-red-800 border-red-200';
      case 'high': return 'bg-red-50 text-red-700 border-red-100';
      case 'medium': return 'bg-amber-50 text-amber-700 border-amber-100';
      case 'low': return 'bg-green-50 text-green-700 border-green-100';
      default: return 'bg-gray-50 text-gray-700 border-gray-100';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'active': return <AlertCircle className="h-5 w-5 text-red-500" />;
      case 'resolved': return <CheckCircle className="h-5 w-5 text-green-500" />;
      case 'monitoring': return <Clock className="h-5 w-5 text-amber-500" />;
      default: return <AlertCircle className="h-5 w-5 text-gray-500" />;
    }
  };

  const generateAIMessage = (incident: Partial<EmergencyIncident>) => {
    setIsGeneratingMessage(true);
    setTimeout(() => {
      const messages = {
        fire: `🚨 FIRE ALERT: A fire alarm has been activated at ${incident.location}. All students and staff in the affected area are evacuating safely. Emergency responders are on scene. Parents will receive updates every 15 minutes until resolved. Your child's safety is our priority.`,
        medical: `🏥 MEDICAL EMERGENCY: Medical assistance is being provided at ${incident.location}. The situation is contained and emergency medical services are responding. All other areas remain secure. We will notify parents of affected students directly.`,
        security: `🔒 SECURITY ALERT: A security incident is being addressed at ${incident.location}. Campus security and local authorities are managing the situation. All students are safe and accounted for. Regular updates will follow.`,
        weather: `⛈️ WEATHER ALERT: Severe weather conditions detected. All students are sheltering safely in designated areas. Outdoor activities are suspended. Parents will be notified when normal operations resume.`,
        lockdown: `🔐 LOCKDOWN ACTIVE: Campus is under precautionary lockdown. All students and staff are secure in their current locations. Law enforcement is coordinating response. We will provide updates every 10 minutes.`
      };
      
      setAiMessage(messages[incident.type as keyof typeof messages] || 'Emergency notification generated by AI system.');
      setIsGeneratingMessage(false);
    }, 2000);
  };

  const createIncident = () => {
    if (!newIncident.location || !newIncident.description) return;

    const incident: EmergencyIncident = {
      id: Date.now().toString(),
      ...newIncident,
      timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19),
      status: 'active',
      affectedStudents: Math.floor(Math.random() * 500) + 50,
      notificationsSent: 0
    };

    setIncidents([incident, ...incidents]);
    generateAIMessage(incident);
    setNewIncident({ type: 'medical', severity: 'medium', location: '', description: '' });
  };

  return (
    <div className="space-y-6">
      {/* Status Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center">
            <AlertTriangle className="h-8 w-8 text-red-500" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Active Incidents</p>
              <p className="text-2xl font-bold text-gray-900">
                {incidents.filter(i => i.status === 'active').length}
              </p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center">
            <Users className="h-8 w-8 text-blue-500" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Students Tracked</p>
              <p className="text-2xl font-bold text-gray-900">2,847</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center">
            <Send className="h-8 w-8 text-green-500" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Notifications Sent</p>
              <p className="text-2xl font-bold text-gray-900">
                {incidents.reduce((sum, i) => sum + i.notificationsSent, 0)}
              </p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center">
            <Zap className="h-8 w-8 text-purple-500" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Response Time</p>
              <p className="text-2xl font-bold text-gray-900">1.2m</p>
            </div>
          </div>
        </div>
      </div>

      {/* Create New Incident */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Create Emergency Alert</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Type</label>
            <select
              value={newIncident.type}
              onChange={(e) => setNewIncident({...newIncident, type: e.target.value as any})}
              className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
            >
              <option value="medical">Medical</option>
              <option value="fire">Fire</option>
              <option value="security">Security</option>
              <option value="weather">Weather</option>
              <option value="lockdown">Lockdown</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Severity</label>
            <select
              value={newIncident.severity}
              onChange={(e) => setNewIncident({...newIncident, severity: e.target.value as any})}
              className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>

          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
            <input
              type="text"
              value={newIncident.location}
              onChange={(e) => setNewIncident({...newIncident, location: e.target.value})}
              placeholder="e.g., Main Building - 2nd Floor"
              className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
            />
          </div>
        </div>

        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
          <textarea
            value={newIncident.description}
            onChange={(e) => setNewIncident({...newIncident, description: e.target.value})}
            placeholder="Detailed description of the emergency situation..."
            rows={3}
            className="w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
          />
        </div>

        <button
          onClick={createIncident}
          disabled={!newIncident.location || !newIncident.description}
          className="bg-red-600 text-white px-6 py-2 rounded-md hover:bg-red-700 disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center"
        >
          <AlertTriangle className="h-4 w-4 mr-2" />
          Create Emergency Alert
        </button>
      </div>

      {/* AI Generated Message */}
      {aiMessage && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <div className="flex items-start">
            <Zap className="h-5 w-5 text-blue-500 mt-1 mr-3 flex-shrink-0" />
            <div className="flex-1">
              <h4 className="font-medium text-blue-900 mb-2">AI-Generated Parent Notification</h4>
              <p className="text-blue-800 mb-4">{aiMessage}</p>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 text-sm">
                Send to All Parents
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Active Incidents */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900">Emergency Incidents</h3>
        </div>
        <div className="divide-y divide-gray-200">
          {incidents.map((incident) => (
            <div key={incident.id} className="p-6 hover:bg-gray-50 transition-colors">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center mb-2">
                    {getStatusIcon(incident.status)}
                    <span className={`ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${getSeverityColor(incident.severity)}`}>
                      {incident.severity.toUpperCase()}
                    </span>
                    <span className="ml-2 text-sm text-gray-600 capitalize">{incident.type}</span>
                  </div>
                  <div className="flex items-center text-sm text-gray-600 mb-2">
                    <MapPin className="h-4 w-4 mr-1" />
                    {incident.location}
                  </div>
                  <p className="text-gray-900 mb-3">{incident.description}</p>
                  <div className="flex items-center space-x-4 text-sm text-gray-600">
                    <div className="flex items-center">
                      <Clock className="h-4 w-4 mr-1" />
                      {incident.timestamp}
                    </div>
                    <div className="flex items-center">
                      <Users className="h-4 w-4 mr-1" />
                      {incident.affectedStudents} students affected
                    </div>
                    <div className="flex items-center">
                      <Send className="h-4 w-4 mr-1" />
                      {incident.notificationsSent} notifications sent
                    </div>
                  </div>
                </div>
                <div className="ml-4 flex-shrink-0">
                  <button className="text-blue-600 hover:text-blue-800 text-sm font-medium">
                    Manage
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default EmergencyDashboard;